# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Render PCB

on:
  push:
    paths:
      - '*.kicad_pcb'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make all
      - uses: EndBug/add-and-commit@v9
        with:
          default:author: github_actor
          message: 'Render PCB'
          add: 'assets/*.png'
      
